/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ApiBatchTaskModel {
    'id': number;
    'apiName': string;
    'onSuccess': number;
    'onFail': number;
    'type'?: ApiBatchTaskModel.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "onSuccess",
            "baseName": "on_success",
            "type": "number"
        },
        {
            "name": "onFail",
            "baseName": "on_fail",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiBatchTaskModel.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ApiBatchTaskModel.attributeTypeMap;
    }
}

export namespace ApiBatchTaskModel {
    export enum TypeEnum {
        Unknown = <any> 'Unknown',
        Task = <any> 'Task',
        Import = <any> 'Import',
        Export = <any> 'Export'
    }
}
