/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ApiNotificationModel {
    'type': ApiNotificationModel.TypeEnum;
    'groups'?: Array<string>;
    'emails'?: Array<string>;
    'includeProcessDetails'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiNotificationModel.TypeEnum"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<string>"
        },
        {
            "name": "emails",
            "baseName": "emails",
            "type": "Array<string>"
        },
        {
            "name": "includeProcessDetails",
            "baseName": "include_process_details",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ApiNotificationModel.attributeTypeMap;
    }
}

export namespace ApiNotificationModel {
    export enum TypeEnum {
        Unknown = <any> 'Unknown',
        NoFile = <any> 'NoFile',
        Error = <any> 'Error',
        Failure = <any> 'Failure',
        Complete = <any> 'Complete'
    }
}
