/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ApiTaskAdvancedOptions {
    'includeSequenceNumber'?: boolean;
    'sequenceNumber'?: number;
    'overwriteExistingFile'?: boolean;
    'noDataHandling'?: ApiTaskAdvancedOptions.NoDataHandlingEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "includeSequenceNumber",
            "baseName": "include_sequence_number",
            "type": "boolean"
        },
        {
            "name": "sequenceNumber",
            "baseName": "sequence_number",
            "type": "number"
        },
        {
            "name": "overwriteExistingFile",
            "baseName": "overwrite_existing_file",
            "type": "boolean"
        },
        {
            "name": "noDataHandling",
            "baseName": "no_data_handling",
            "type": "ApiTaskAdvancedOptions.NoDataHandlingEnum"
        }    ];

    static getAttributeTypeMap() {
        return ApiTaskAdvancedOptions.attributeTypeMap;
    }
}

export namespace ApiTaskAdvancedOptions {
    export enum NoDataHandlingEnum {
        Unknown = <any> 'Unknown',
        Continue = <any> 'Continue',
        Skip = <any> 'Skip',
        Fail = <any> 'Fail'
    }
}
