/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ContentDetailsResponseModel {
    /**
    * Name of the Content.
    */
    'name'?: string;
    /**
    * Description of the Content.
    */
    'description'?: string;
    /**
    * API name of the Content.
    */
    'apiName'?: string;
    /**
    * Tags  of the Content.
    */
    'tags'?: Array<string>;
    /**
    * Channel type of the Content.
    */
    'type'?: ContentDetailsResponseModel.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ContentDetailsResponseModel.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ContentDetailsResponseModel.attributeTypeMap;
    }
}

export namespace ContentDetailsResponseModel {
    export enum TypeEnum {
        Unknown = <any> 'Unknown',
        Email = <any> 'Email',
        Page = <any> 'Page',
        MobilePush = <any> 'MobilePush',
        Sms = <any> 'Sms'
    }
}
