/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { DataSelectionDTO } from './dataSelectionDTO';

export class ContentDTO {
    'languageCode'?: string;
    'dataSelectionContent'?: Array<DataSelectionDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "languageCode",
            "baseName": "language_code",
            "type": "string"
        },
        {
            "name": "dataSelectionContent",
            "baseName": "data_selection_content",
            "type": "Array<DataSelectionDTO>"
        }    ];

    static getAttributeTypeMap() {
        return ContentDTO.attributeTypeMap;
    }
}

