/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiExportTaskDataSourceModel } from './apiExportTaskDataSourceModel';
import { ApiExportTaskOutputModel } from './apiExportTaskOutputModel';
import { ApiNotificationModel } from './apiNotificationModel';
import { ApiScheduleModel } from './apiScheduleModel';
import { ApiTaskAdvancedOptions } from './apiTaskAdvancedOptions';
import { ApiTriggerCustomEventModel } from './apiTriggerCustomEventModel';
import { ApiTriggerFileModel } from './apiTriggerFileModel';
import { ApiZipAndEncryptModel } from './apiZipAndEncryptModel';

export class CreateExportTaskApiRequestModel {
    'dataSource'?: ApiExportTaskDataSourceModel;
    'output'?: ApiExportTaskOutputModel;
    'options'?: ApiTaskAdvancedOptions;
    'triggerFile'?: ApiTriggerFileModel;
    'zipAndEncrypt'?: ApiZipAndEncryptModel;
    'destination': string;
    'subfolder'?: string;
    'name': string;
    'description'?: string;
    'tags'?: Array<string>;
    'apiName': string;
    'scheduler'?: number;
    'schedule'?: ApiScheduleModel;
    'notifications': Array<ApiNotificationModel>;
    'triggerJourneyAfterExecution'?: string;
    'triggerCustomEventAfterExecution'?: ApiTriggerCustomEventModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataSource",
            "baseName": "data_source",
            "type": "ApiExportTaskDataSourceModel"
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "ApiExportTaskOutputModel"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ApiTaskAdvancedOptions"
        },
        {
            "name": "triggerFile",
            "baseName": "trigger_file",
            "type": "ApiTriggerFileModel"
        },
        {
            "name": "zipAndEncrypt",
            "baseName": "zip_and_encrypt",
            "type": "ApiZipAndEncryptModel"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "string"
        },
        {
            "name": "subfolder",
            "baseName": "subfolder",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "scheduler",
            "baseName": "scheduler",
            "type": "number"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "ApiScheduleModel"
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "Array<ApiNotificationModel>"
        },
        {
            "name": "triggerJourneyAfterExecution",
            "baseName": "trigger_journey_after_execution",
            "type": "string"
        },
        {
            "name": "triggerCustomEventAfterExecution",
            "baseName": "trigger_custom_event_after_execution",
            "type": "ApiTriggerCustomEventModel"
        }    ];

    static getAttributeTypeMap() {
        return CreateExportTaskApiRequestModel.attributeTypeMap;
    }
}

