/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CreateContentPropertyModel } from './createContentPropertyModel';
import { CreateMobileMessagePropertyModel } from './createMobileMessagePropertyModel';
import { MobileMessageContentModel } from './mobileMessageContentModel';

export class CreateMobileMessageModel {
    'mobileProperties': CreateMobileMessagePropertyModel;
    'content': { [key: string]: MobileMessageContentModel; };
    'properties': CreateContentPropertyModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobileProperties",
            "baseName": "mobile_properties",
            "type": "CreateMobileMessagePropertyModel"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "{ [key: string]: MobileMessageContentModel; }"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "CreateContentPropertyModel"
        }    ];

    static getAttributeTypeMap() {
        return CreateMobileMessageModel.attributeTypeMap;
    }
}

