/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiColumnMappingModel } from './apiColumnMappingModel';
import { ApiImportTaskAdvancedOptionsModel } from './apiImportTaskAdvancedOptionsModel';
import { ApiImportTaskDataProcessingModel } from './apiImportTaskDataProcessingModel';
import { ApiImportTaskDestinationModel } from './apiImportTaskDestinationModel';
import { ApiImportTaskFileOptionsModel } from './apiImportTaskFileOptionsModel';
import { ApiNotificationModel } from './apiNotificationModel';
import { ApiProcessingFoldersModel } from './apiProcessingFoldersModel';
import { ApiRejectManagementModel } from './apiRejectManagementModel';
import { ApiScheduleModel } from './apiScheduleModel';
import { ApiTriggerCustomEventModel } from './apiTriggerCustomEventModel';
import { ApiUnzipAndDecryptModel } from './apiUnzipAndDecryptModel';

export class CreateImportTaskApiRequestModel {
    'source': string;
    'subfolder'?: string;
    'options'?: ApiImportTaskAdvancedOptionsModel;
    'fileType'?: CreateImportTaskApiRequestModel.FileTypeEnum;
    'fileOptions'?: ApiImportTaskFileOptionsModel;
    'columnMapping'?: Array<ApiColumnMappingModel>;
    'fileDescriptor'?: string;
    'processingFolders'?: ApiProcessingFoldersModel;
    'unzipAndDecrypt'?: ApiUnzipAndDecryptModel;
    'destination': ApiImportTaskDestinationModel;
    'dataProcessing'?: ApiImportTaskDataProcessingModel;
    'rejectManagement'?: ApiRejectManagementModel;
    'name': string;
    'description'?: string;
    'tags'?: Array<string>;
    'apiName': string;
    'scheduler'?: number;
    'schedule'?: ApiScheduleModel;
    'notifications': Array<ApiNotificationModel>;
    'triggerJourneyAfterExecution'?: string;
    'triggerCustomEventAfterExecution'?: ApiTriggerCustomEventModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "subfolder",
            "baseName": "subfolder",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ApiImportTaskAdvancedOptionsModel"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "CreateImportTaskApiRequestModel.FileTypeEnum"
        },
        {
            "name": "fileOptions",
            "baseName": "file_options",
            "type": "ApiImportTaskFileOptionsModel"
        },
        {
            "name": "columnMapping",
            "baseName": "column_mapping",
            "type": "Array<ApiColumnMappingModel>"
        },
        {
            "name": "fileDescriptor",
            "baseName": "file_descriptor",
            "type": "string"
        },
        {
            "name": "processingFolders",
            "baseName": "processing_folders",
            "type": "ApiProcessingFoldersModel"
        },
        {
            "name": "unzipAndDecrypt",
            "baseName": "unzip_and_decrypt",
            "type": "ApiUnzipAndDecryptModel"
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "ApiImportTaskDestinationModel"
        },
        {
            "name": "dataProcessing",
            "baseName": "data_processing",
            "type": "ApiImportTaskDataProcessingModel"
        },
        {
            "name": "rejectManagement",
            "baseName": "reject_management",
            "type": "ApiRejectManagementModel"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "scheduler",
            "baseName": "scheduler",
            "type": "number"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "ApiScheduleModel"
        },
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "Array<ApiNotificationModel>"
        },
        {
            "name": "triggerJourneyAfterExecution",
            "baseName": "trigger_journey_after_execution",
            "type": "string"
        },
        {
            "name": "triggerCustomEventAfterExecution",
            "baseName": "trigger_custom_event_after_execution",
            "type": "ApiTriggerCustomEventModel"
        }    ];

    static getAttributeTypeMap() {
        return CreateImportTaskApiRequestModel.attributeTypeMap;
    }
}

export namespace CreateImportTaskApiRequestModel {
    export enum FileTypeEnum {
        Unknown = <any> 'Unknown',
        Delimited = <any> 'Delimited',
        Json = <any> 'Json',
        Xml = <any> 'Xml',
        Excel = <any> 'Excel',
        Rss = <any> 'Rss'
    }
}
