/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class DataSelectionDTO {
    'name'?: string;
    'insertData'?: Array<object>;
    'selectData'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "insertData",
            "baseName": "insert_data",
            "type": "Array<object>"
        },
        {
            "name": "selectData",
            "baseName": "select_data",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return DataSelectionDTO.attributeTypeMap;
    }
}

