/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Field {
    /**
    * The name of the field.
    */
    'name'?: string;
    /**
    * The length of the field
    */
    'length'?: number;
    /**
    * Data type of the field
    */
    'dataType'?: Field.DataTypeEnum;
    /**
    * Description about the field
    */
    'description'?: string;
    /**
    * Allow null
    */
    'allowNull'?: boolean;
    'content'?: Field.ContentEnum;
    'optionlist'?: string;
    'valueDefinition'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number"
        },
        {
            "name": "dataType",
            "baseName": "data_type",
            "type": "Field.DataTypeEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "allowNull",
            "baseName": "allow_null",
            "type": "boolean"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "Field.ContentEnum"
        },
        {
            "name": "optionlist",
            "baseName": "optionlist",
            "type": "string"
        },
        {
            "name": "valueDefinition",
            "baseName": "value_definition",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Field.attributeTypeMap;
    }
}

export namespace Field {
    export enum DataTypeEnum {
        Unknown = <any> 'Unknown',
        Boolean = <any> 'Boolean',
        Numeric = <any> 'Numeric',
        Long = <any> 'Long',
        Float = <any> 'Float',
        Date = <any> 'Date',
        DateTime = <any> 'DateTime',
        Text = <any> 'Text',
        LongText = <any> 'LongText',
        Json = <any> 'Json'
    }
    export enum ContentEnum {
        Unknown = <any> 'Unknown',
        Free = <any> 'Free',
        Single = <any> 'Single',
        Multi = <any> 'Multi',
        ComputedNonPersisted = <any> 'ComputedNonPersisted',
        ComputedPersisted = <any> 'ComputedPersisted',
        Lookup = <any> 'Lookup'
    }
}
