/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class InvalidRecordModel {
    /**
    * Index of the invalid record
    */
    'recordIndex'?: number;
    /**
    * Name of the field that contains the invalid data
    */
    'fieldName'?: string;
    /**
    * Message containing information about the error
    */
    'message'?: string;
    /**
    * Validation code indicating the error.
    */
    'validationCode'?: InvalidRecordModel.ValidationCodeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recordIndex",
            "baseName": "record_index",
            "type": "number"
        },
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "validationCode",
            "baseName": "validation_code",
            "type": "InvalidRecordModel.ValidationCodeEnum"
        }    ];

    static getAttributeTypeMap() {
        return InvalidRecordModel.attributeTypeMap;
    }
}

export namespace InvalidRecordModel {
    export enum ValidationCodeEnum {
        Unknown = <any> 'Unknown',
        InvalidFieldCount = <any> 'InvalidFieldCount',
        MaxStringLengthExceeded = <any> 'MaxStringLengthExceeded',
        InvalidType = <any> 'InvalidType'
    }
}
