/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class JourneyEntryPointParameter {
    /**
    * The name of the parameter.
    */
    'name'?: string;
    /**
    * An indicator on wheter the parameter is required or not when used to trigger the entry point.
    */
    'required'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return JourneyEntryPointParameter.attributeTypeMap;
    }
}

