/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { JourneyEntryPointInfo } from './journeyEntryPointInfo';

export class JourneyEntryPointInfoResponse {
    /**
    * Can contain some important system information.
    */
    'systemInfo'?: string;
    'model'?: JourneyEntryPointInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "systemInfo",
            "baseName": "system_info",
            "type": "string"
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "JourneyEntryPointInfo"
        }    ];

    static getAttributeTypeMap() {
        return JourneyEntryPointInfoResponse.attributeTypeMap;
    }
}

