/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { DeduplicationDTO } from './deduplicationDTO';
import { SchedulingDTO } from './schedulingDTO';
import { TopDTO } from './topDTO';
import { WaveDTO } from './waveDTO';

export class JourneyDTO {
    'apiName': string;
    'name': string;
    'launchState'?: JourneyDTO.LaunchStateEnum;
    'scheduling'?: SchedulingDTO;
    'type'?: JourneyDTO.TypeEnum;
    'campaignAnalyticsTag'?: string;
    'messageAnalyticsTag'?: string;
    'deduplication'?: DeduplicationDTO;
    'sendInWaves'?: WaveDTO;
    'sendingLimit'?: TopDTO;
    'disableFlags'?: boolean;
    'disableTracking'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "launchState",
            "baseName": "launch_state",
            "type": "JourneyDTO.LaunchStateEnum"
        },
        {
            "name": "scheduling",
            "baseName": "scheduling",
            "type": "SchedulingDTO"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "JourneyDTO.TypeEnum"
        },
        {
            "name": "campaignAnalyticsTag",
            "baseName": "campaign_analytics_tag",
            "type": "string"
        },
        {
            "name": "messageAnalyticsTag",
            "baseName": "message_analytics_tag",
            "type": "string"
        },
        {
            "name": "deduplication",
            "baseName": "deduplication",
            "type": "DeduplicationDTO"
        },
        {
            "name": "sendInWaves",
            "baseName": "send_in_waves",
            "type": "WaveDTO"
        },
        {
            "name": "sendingLimit",
            "baseName": "sending_limit",
            "type": "TopDTO"
        },
        {
            "name": "disableFlags",
            "baseName": "disable_flags",
            "type": "boolean"
        },
        {
            "name": "disableTracking",
            "baseName": "disable_tracking",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return JourneyDTO.attributeTypeMap;
    }
}

export namespace JourneyDTO {
    export enum LaunchStateEnum {
        None = <any> 'none',
        Launch = <any> 'launch',
        Schedule = <any> 'schedule'
    }
    export enum TypeEnum {
        Unknown = <any> 'unknown',
        Singlebatch = <any> 'singlebatch',
        Transactional = <any> 'transactional',
        Ab = <any> 'ab',
        Recurring = <any> 'recurring',
        Custom = <any> 'custom'
    }
}
