/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Journey {
    /**
    * The api_name of the journey
    */
    'apiName'?: string;
    /**
    * The type of journey
    */
    'type'?: Journey.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Journey.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Journey.attributeTypeMap;
    }
}

export namespace Journey {
    export enum TypeEnum {
        Unknown = <any> 'unknown',
        Singlebatch = <any> 'singlebatch',
        Transactional = <any> 'transactional',
        Ab = <any> 'ab',
        Recurring = <any> 'recurring',
        Custom = <any> 'custom'
    }
}
