/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* Represents json field schema api model.
*/
export class JsonFieldSchemaApiRequestModel {
    /**
    * Name of the json field.
    */
    'name': string;
    /**
    * Indicates whether the value of json field required or not.
    */
    'required'?: boolean;
    /**
    * Input type of json field.
    */
    'inputType': JsonFieldSchemaApiRequestModel.InputTypeEnum;
    /**
    * Child data for Array type of json field.
    */
    'childData'?: Array<JsonFieldSchemaApiRequestModel>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean"
        },
        {
            "name": "inputType",
            "baseName": "input_type",
            "type": "JsonFieldSchemaApiRequestModel.InputTypeEnum"
        },
        {
            "name": "childData",
            "baseName": "child_data",
            "type": "Array<JsonFieldSchemaApiRequestModel>"
        }    ];

    static getAttributeTypeMap() {
        return JsonFieldSchemaApiRequestModel.attributeTypeMap;
    }
}

export namespace JsonFieldSchemaApiRequestModel {
    export enum InputTypeEnum {
        Unknown = <any> 'Unknown',
        Boolean = <any> 'Boolean',
        Numeric = <any> 'Numeric',
        Long = <any> 'Long',
        Float = <any> 'Float',
        Date = <any> 'Date',
        DateTime = <any> 'DateTime',
        Text = <any> 'Text',
        LongText = <any> 'LongText',
        Array = <any> 'Array'
    }
}
