/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Labels {
    /**
    * Name of the label.
    */
    'label'?: string;
    /**
    * A set of translations consisting of key value pairs where key is a language code and value is translation for that language code.
    */
    'translations'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return Labels.attributeTypeMap;
    }
}

