/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class List {
    /**
    * The id of the list.
    */
    'id'?: number;
    /**
    * The type of the list.
    */
    'type'?: List.TypeEnum;
    /**
    * The Api name for a list.
    */
    'apiName'?: string;
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "List.TypeEnum"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return List.attributeTypeMap;
    }
}

export namespace List {
    export enum TypeEnum {
        Unknown = <any> 'Unknown',
        Userlist = <any> 'Userlist',
        Datalist = <any> 'Datalist',
        DataSelectionList = <any> 'DataSelectionList',
        Optionlist = <any> 'Optionlist',
        Devicelist = <any> 'Devicelist'
    }
}
