/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { GetListDetailsEmailQuality } from './getListDetailsEmailQuality';

export class ListDetailsResponseModel {
    /**
    * API name of the list.
    */
    'apiName'?: string;
    /**
    * Name of the list.
    */
    'name'?: string;
    /**
    * Type of the list.
    */
    'type'?: ListDetailsResponseModel.TypeEnum;
    /**
    * Description about the list.
    */
    'description'?: string;
    /**
    * Tags associated with the list.
    */
    'tags'?: Array<string>;
    'emailQualityConfiguration'?: GetListDetailsEmailQuality;
    /**
    * Enforce segment selection.
    */
    'enforceSegmentSelection'?: boolean;
    /**
    * API name of Tag list.
    */
    'taglistApiName'?: string;
    /**
    * Represents organizations associated with the list and can be accessed by the API Application.
    */
    'organizations'?: Array<string>;
    /**
    * Represents number of organizations associated with the list and cannot be accessed by the API Application.
    */
    'notAccessibleOrganizationsCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ListDetailsResponseModel.TypeEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "emailQualityConfiguration",
            "baseName": "email_quality_configuration",
            "type": "GetListDetailsEmailQuality"
        },
        {
            "name": "enforceSegmentSelection",
            "baseName": "enforce_segment_selection",
            "type": "boolean"
        },
        {
            "name": "taglistApiName",
            "baseName": "taglist_api_name",
            "type": "string"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<string>"
        },
        {
            "name": "notAccessibleOrganizationsCount",
            "baseName": "not_accessible_organizations_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListDetailsResponseModel.attributeTypeMap;
    }
}

export namespace ListDetailsResponseModel {
    export enum TypeEnum {
        Unknown = <any> 'Unknown',
        Userlist = <any> 'Userlist',
        Datalist = <any> 'Datalist',
        DataSelectionList = <any> 'DataSelectionList',
        Optionlist = <any> 'Optionlist',
        Devicelist = <any> 'Devicelist'
    }
}
