/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Lookup {
    /**
    * Scope name, e.g.: <b>MASTER</b>
    */
    'scope': string;
    /**
    * A field that exists for the given scope.
    */
    'field': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Lookup.attributeTypeMap;
    }
}

