/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class RelationCustomFiltersDTO {
    'list1'?: string;
    'field1'?: string;
    'operator'?: RelationCustomFiltersDTO.OperatorEnum;
    'list2'?: string;
    'field2'?: string;
    'value'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "list1",
            "baseName": "list1",
            "type": "string"
        },
        {
            "name": "field1",
            "baseName": "field1",
            "type": "string"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "RelationCustomFiltersDTO.OperatorEnum"
        },
        {
            "name": "list2",
            "baseName": "list2",
            "type": "string"
        },
        {
            "name": "field2",
            "baseName": "field2",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RelationCustomFiltersDTO.attributeTypeMap;
    }
}

export namespace RelationCustomFiltersDTO {
    export enum OperatorEnum {
        Unknown = <any> 'Unknown',
        EqualTo = <any> 'EqualTo',
        NotEqualTo = <any> 'NotEqualTo',
        GreaterThan = <any> 'GreaterThan',
        GreaterThanOrEqualTo = <any> 'GreaterThanOrEqualTo',
        LessThan = <any> 'LessThan',
        LessThanOrEqualTo = <any> 'LessThanOrEqualTo',
        Like = <any> 'Like',
        IsNull = <any> 'IsNull',
        IsNotNull = <any> 'IsNotNull',
        IsEmpty = <any> 'IsEmpty',
        IsNotEmpty = <any> 'IsNotEmpty'
    }
}
