/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Labels } from './labels';

export class RetrieveLabelsSuccessExampleResponse {
    /**
    * Collection of dictionaries.
    */
    'labels'?: Array<Labels>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<Labels>"
        }    ];

    static getAttributeTypeMap() {
        return RetrieveLabelsSuccessExampleResponse.attributeTypeMap;
    }
}

