/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Segment {
    /**
    * Type of the segment.
    */
    'segmentType'?: Segment.SegmentTypeEnum;
    /**
    * Segment API name.
    */
    'apiName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "segmentType",
            "baseName": "segment_type",
            "type": "Segment.SegmentTypeEnum"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Segment.attributeTypeMap;
    }
}

export namespace Segment {
    export enum SegmentTypeEnum {
        Unknown = <any> 'Unknown',
        Dynamic = <any> 'Dynamic',
        Static = <any> 'Static',
        External = <any> 'External'
    }
}
