/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class SendingLimit {
    'type'?: string;
    'percentage'?: number;
    'count'?: number;
    'sortSelection'?: string;
    'sortField'?: string;
    'sortDescending'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "sortSelection",
            "baseName": "sort_selection",
            "type": "string"
        },
        {
            "name": "sortField",
            "baseName": "sort_field",
            "type": "string"
        },
        {
            "name": "sortDescending",
            "baseName": "sort_descending",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SendingLimit.attributeTypeMap;
    }
}

