/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class UpdateFtpMediumApiRequestModel {
    /**
    * Type of Ftp Medium - FTPS, SFTP, FTPSImplicit
    */
    'ftpType'?: UpdateFtpMediumApiRequestModel.FtpTypeEnum;
    /**
    * Address of the FTP server
    */
    'server'?: string;
    /**
    * Login for accessing FTP server
    */
    'login'?: string;
    /**
    * Password associated with the Login to access the FTP server
    */
    'password'?: string;
    /**
    * Path of a subfolder on FTP server
    */
    'subfolder'?: string;
    /**
    * API Name associated with the medium
    */
    'apiName'?: string;
    /**
    * Name of the medium
    */
    'name'?: string;
    /**
    * List of organizations linked to the medium
    */
    'organizations'?: Array<string>;
    /**
    * Description of the medium
    */
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ftpType",
            "baseName": "ftp_type",
            "type": "UpdateFtpMediumApiRequestModel.FtpTypeEnum"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "subfolder",
            "baseName": "subfolder",
            "type": "string"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<string>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateFtpMediumApiRequestModel.attributeTypeMap;
    }
}

export namespace UpdateFtpMediumApiRequestModel {
    export enum FtpTypeEnum {
        Unknown = <any> 'Unknown',
        Ftps = <any> 'Ftps',
        FtpsImplicit = <any> 'FtpsImplicit',
        Sftp = <any> 'Sftp'
    }
}
