/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiEmailQualityModel } from './apiEmailQualityModel';

export class UpdateListRequestModel {
    /**
    * API name of the list.
    */
    'apiName'?: string;
    /**
    * Name of the list.
    */
    'name'?: string;
    /**
    * Description about the list.
    */
    'description'?: string;
    /**
    * Tags associated with the list.
    */
    'tags'?: Array<string>;
    'emailQualityConfiguration'?: ApiEmailQualityModel;
    /**
    * Enforce segment selection.
    */
    'enforceSegmentSelection'?: boolean;
    /**
    * Taglist api name.
    */
    'taglistApiName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "emailQualityConfiguration",
            "baseName": "email_quality_configuration",
            "type": "ApiEmailQualityModel"
        },
        {
            "name": "enforceSegmentSelection",
            "baseName": "enforce_segment_selection",
            "type": "boolean"
        },
        {
            "name": "taglistApiName",
            "baseName": "taglist_api_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateListRequestModel.attributeTypeMap;
    }
}

