/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiEmailQualityActionModel } from './apiEmailQualityActionModel';

export class ApiEmailQualityModel {
    'type'?: ApiEmailQualityModel.TypeEnum;
    'bounceScope'?: string;
    'actions'?: Array<ApiEmailQualityActionModel>;
    'bounceStoredProcedures'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ApiEmailQualityModel.TypeEnum"
        },
        {
            "name": "bounceScope",
            "baseName": "bounce_scope",
            "type": "string"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<ApiEmailQualityActionModel>"
        },
        {
            "name": "bounceStoredProcedures",
            "baseName": "bounce_stored_procedures",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ApiEmailQualityModel.attributeTypeMap;
    }
}

export namespace ApiEmailQualityModel {
    export enum TypeEnum {
        Defensive = <any> 'Defensive',
        Normal = <any> 'Normal',
        Aggressive = <any> 'Aggressive',
        Custom = <any> 'Custom'
    }
}
