/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ApiScheduleModel {
    'startDate'?: Date;
    'endDate'?: Date;
    'scheduleType': ApiScheduleModel.ScheduleTypeEnum;
    'hours': Array<number>;
    'days': Array<number>;
    'startTime': string;
    'period': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "Date"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "Date"
        },
        {
            "name": "scheduleType",
            "baseName": "schedule_type",
            "type": "ApiScheduleModel.ScheduleTypeEnum"
        },
        {
            "name": "hours",
            "baseName": "hours",
            "type": "Array<number>"
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "Array<number>"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "period",
            "baseName": "period",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ApiScheduleModel.attributeTypeMap;
    }
}

export namespace ApiScheduleModel {
    export enum ScheduleTypeEnum {
        Unknown = <any> 'Unknown',
        Daily = <any> 'Daily',
        Weekly = <any> 'Weekly',
        Monthly = <any> 'Monthly',
        Periodically = <any> 'Periodically'
    }
}
