/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiExportTaskDataSourceModel } from './apiExportTaskDataSourceModel';
import { ApiExportTaskFileOptionsModel } from './apiExportTaskFileOptionsModel';

export class ApiTriggerFileModel {
    'dataSource'?: ApiExportTaskDataSourceModel;
    'extension'?: string;
    'fileOptions'?: ApiExportTaskFileOptionsModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataSource",
            "baseName": "data_source",
            "type": "ApiExportTaskDataSourceModel"
        },
        {
            "name": "extension",
            "baseName": "extension",
            "type": "string"
        },
        {
            "name": "fileOptions",
            "baseName": "file_options",
            "type": "ApiExportTaskFileOptionsModel"
        }    ];

    static getAttributeTypeMap() {
        return ApiTriggerFileModel.attributeTypeMap;
    }
}

