/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ApiPgpDecryptionModel } from './apiPgpDecryptionModel';

export class ApiUnzipAndDecryptModel {
    'mode': ApiUnzipAndDecryptModel.ModeEnum;
    'unzipFilter'?: string;
    'pgpDecryption'?: ApiPgpDecryptionModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mode",
            "baseName": "mode",
            "type": "ApiUnzipAndDecryptModel.ModeEnum"
        },
        {
            "name": "unzipFilter",
            "baseName": "unzip_filter",
            "type": "string"
        },
        {
            "name": "pgpDecryption",
            "baseName": "pgp_decryption",
            "type": "ApiPgpDecryptionModel"
        }    ];

    static getAttributeTypeMap() {
        return ApiUnzipAndDecryptModel.attributeTypeMap;
    }
}

export namespace ApiUnzipAndDecryptModel {
    export enum ModeEnum {
        Unknown = <any> 'Unknown',
        Unzip = <any> 'Unzip',
        Decrypt = <any> 'Decrypt',
        UnzipAndDecrypt = <any> 'UnzipAndDecrypt',
        DecryptAndUnzip = <any> 'DecryptAndUnzip'
    }
}
