/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CreateContentPropertyModel } from './createContentPropertyModel';
import { EmailMessageContentModel } from './emailMessageContentModel';
import { EmailMessageHeaderModel } from './emailMessageHeaderModel';

export class CreateEmailMessageModel {
    'headers': { [key: string]: Array<EmailMessageHeaderModel>; };
    'content': EmailMessageContentModel;
    'properties': CreateContentPropertyModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: Array<EmailMessageHeaderModel>; }"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "EmailMessageContentModel"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "CreateContentPropertyModel"
        }    ];

    static getAttributeTypeMap() {
        return CreateEmailMessageModel.attributeTypeMap;
    }
}

