/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CreateMobileMessagePropertyModel {
    'distributionType': CreateMobileMessagePropertyModel.DistributionTypeEnum;
    'customInAppContent': boolean;
    'inAppContentType'?: CreateMobileMessagePropertyModel.InAppContentTypeEnum;
    'expirationDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "distributionType",
            "baseName": "distribution_type",
            "type": "CreateMobileMessagePropertyModel.DistributionTypeEnum"
        },
        {
            "name": "customInAppContent",
            "baseName": "custom_in_app_content",
            "type": "boolean"
        },
        {
            "name": "inAppContentType",
            "baseName": "in_app_content_type",
            "type": "CreateMobileMessagePropertyModel.InAppContentTypeEnum"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateMobileMessagePropertyModel.attributeTypeMap;
    }
}

export namespace CreateMobileMessagePropertyModel {
    export enum DistributionTypeEnum {
        Unknown = <any> 'Unknown',
        MobilePushAndInApp = <any> 'MobilePushAndInApp',
        InApp = <any> 'InApp',
        InAppIfPushUnavailable = <any> 'InAppIfPushUnavailable',
        MobilePush = <any> 'MobilePush'
    }
    export enum InAppContentTypeEnum {
        Unknown = <any> 'Unknown',
        Text = <any> 'Text',
        Url = <any> 'Url',
        Image = <any> 'Image',
        Page = <any> 'Page',
        SmartBlock = <any> 'SmartBlock'
    }
}
