/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CreateEmailMessageModel } from './createEmailMessageModel';
import { CreateJourneyModel } from './createJourneyModel';

export class CreateSingleBatchMessageRequestModel {
    'journeyModel': CreateJourneyModel;
    'messageModel': CreateEmailMessageModel;
    'folder': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "journeyModel",
            "baseName": "journey_model",
            "type": "CreateJourneyModel"
        },
        {
            "name": "messageModel",
            "baseName": "message_model",
            "type": "CreateEmailMessageModel"
        },
        {
            "name": "folder",
            "baseName": "folder",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateSingleBatchMessageRequestModel.attributeTypeMap;
    }
}

