/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class DictionaryDetailsResponseModel {
    /**
    * Name of dictionary.
    */
    'name'?: string;
    /**
    * API name of dictionary.
    */
    'apiName'?: string;
    /**
    * Description of dictionary.
    */
    'description'?: string;
    /**
    * Tags of dictionary.
    */
    'tags'?: Array<string>;
    /**
    * Represents organizations associated with the dictionary and can be accessed by the API Application.
    */
    'organizations'?: Array<string>;
    /**
    * Represents number of organizations associated with the dictionary and cannot be accessed by the API Application.
    */
    'notAccessibleOrganizationsCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<string>"
        },
        {
            "name": "notAccessibleOrganizationsCount",
            "baseName": "not_accessible_organizations_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DictionaryDetailsResponseModel.attributeTypeMap;
    }
}

