/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class FtpMediumModel {
    /**
    * Type of the Medium (FTP / REPOSITORY / URL).
    */
    'type'?: FtpMediumModel.TypeEnum;
    /**
    * API name of the Medium.
    */
    'apiName'?: string;
    /**
    * Name of the Medium.
    */
    'name'?: string;
    /**
    * Description.
    */
    'description'?: string;
    /**
    * Represents organizations associated with the medium and can be accessed by the API Application.
    */
    'organizations'?: Array<string>;
    /**
    * Represents number of organizations associated with the medium and cannot be accessed by the API Application.
    */
    'notAccessibleOrganizationsCount'?: number;
    /**
    * Type of ftp mediums (FTPS / FTPSIMPLICIT / SFTP).
    */
    'ftpType'?: FtpMediumModel.FtpTypeEnum;
    /**
    * Name of server.
    */
    'server'?: string;
    /**
    * Name of login user.
    */
    'login'?: string;
    /**
    * subfolder path.
    */
    'subfolder'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "FtpMediumModel.TypeEnum"
        },
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<string>"
        },
        {
            "name": "notAccessibleOrganizationsCount",
            "baseName": "not_accessible_organizations_count",
            "type": "number"
        },
        {
            "name": "ftpType",
            "baseName": "ftp_type",
            "type": "FtpMediumModel.FtpTypeEnum"
        },
        {
            "name": "server",
            "baseName": "server",
            "type": "string"
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string"
        },
        {
            "name": "subfolder",
            "baseName": "subfolder",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FtpMediumModel.attributeTypeMap;
    }
}

export namespace FtpMediumModel {
    export enum TypeEnum {
        Ftp = <any> 'Ftp',
        Repository = <any> 'Repository',
        Url = <any> 'Url'
    }
    export enum FtpTypeEnum {
        Ftps = <any> 'Ftps',
        FtpsImplicit = <any> 'FtpsImplicit',
        Sftp = <any> 'Sftp'
    }
}
