/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { GetListDetailsEmailQualityAction } from './getListDetailsEmailQualityAction';

export class GetListDetailsEmailQuality {
    'emailQualityType'?: GetListDetailsEmailQuality.EmailQualityTypeEnum;
    'invalidEmailSyntax'?: number;
    'nonExistingDomain'?: number;
    'hardBounce'?: number;
    'softBounce'?: number;
    'bounceScope'?: string;
    'emailQualityActions'?: Array<GetListDetailsEmailQualityAction>;
    'bounceStoredProcedures'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailQualityType",
            "baseName": "email_quality_type",
            "type": "GetListDetailsEmailQuality.EmailQualityTypeEnum"
        },
        {
            "name": "invalidEmailSyntax",
            "baseName": "invalid_email_syntax",
            "type": "number"
        },
        {
            "name": "nonExistingDomain",
            "baseName": "non_existing_domain",
            "type": "number"
        },
        {
            "name": "hardBounce",
            "baseName": "hard_bounce",
            "type": "number"
        },
        {
            "name": "softBounce",
            "baseName": "soft_bounce",
            "type": "number"
        },
        {
            "name": "bounceScope",
            "baseName": "bounce_scope",
            "type": "string"
        },
        {
            "name": "emailQualityActions",
            "baseName": "email_quality_actions",
            "type": "Array<GetListDetailsEmailQualityAction>"
        },
        {
            "name": "bounceStoredProcedures",
            "baseName": "bounce_stored_procedures",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return GetListDetailsEmailQuality.attributeTypeMap;
    }
}

export namespace GetListDetailsEmailQuality {
    export enum EmailQualityTypeEnum {
        Defensive = <any> 'Defensive',
        Normal = <any> 'Normal',
        Aggressive = <any> 'Aggressive',
        Custom = <any> 'Custom'
    }
}
