/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class GetOrganizationLanguageModelResponseExample {
    /**
    * The name of the language.
    */
    'name'?: string;
    /**
    * The code of the language.
    */
    'code'?: string;
    /**
    * The locale of the language.
    */
    'locale'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetOrganizationLanguageModelResponseExample.attributeTypeMap;
    }
}

