/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Deduplication } from './deduplication';
import { SendInWaves } from './sendInWaves';
import { SendingLimit } from './sendingLimit';

export class JourneyCreateResponse {
    /**
    * The api_name of the journey
    */
    'apiName'?: string;
    /**
    * The name of the journey
    */
    'name'?: string;
    /**
    * The state of the journey
    */
    'launchState'?: JourneyCreateResponse.LaunchStateEnum;
    /**
    * The type of journey
    */
    'type'?: JourneyCreateResponse.TypeEnum;
    'deduplication'?: Deduplication;
    'sendInWaves'?: SendInWaves;
    'sendingLimit'?: SendingLimit;
    /**
    * This will disable flags
    */
    'disableFlags'?: boolean;
    /**
    * This will disable tracking
    */
    'disableTracking'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiName",
            "baseName": "api_name",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "launchState",
            "baseName": "launch_state",
            "type": "JourneyCreateResponse.LaunchStateEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "JourneyCreateResponse.TypeEnum"
        },
        {
            "name": "deduplication",
            "baseName": "deduplication",
            "type": "Deduplication"
        },
        {
            "name": "sendInWaves",
            "baseName": "send_in_waves",
            "type": "SendInWaves"
        },
        {
            "name": "sendingLimit",
            "baseName": "sending_limit",
            "type": "SendingLimit"
        },
        {
            "name": "disableFlags",
            "baseName": "disable_flags",
            "type": "boolean"
        },
        {
            "name": "disableTracking",
            "baseName": "disable_tracking",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return JourneyCreateResponse.attributeTypeMap;
    }
}

export namespace JourneyCreateResponse {
    export enum LaunchStateEnum {
        None = <any> 'none',
        Launch = <any> 'launch',
        Schedule = <any> 'schedule'
    }
    export enum TypeEnum {
        Unknown = <any> 'unknown',
        Singlebatch = <any> 'singlebatch',
        Transactional = <any> 'transactional',
        Ab = <any> 'ab',
        Recurring = <any> 'recurring',
        Custom = <any> 'custom'
    }
}
