/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { InAppModel } from './inAppModel';
import { MobilePushModel } from './mobilePushModel';

export class MobileMessageContentModel {
    'mobilePush'?: MobilePushModel;
    'inApp'?: InAppModel;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobilePush",
            "baseName": "mobile_push",
            "type": "MobilePushModel"
        },
        {
            "name": "inApp",
            "baseName": "in_app",
            "type": "InAppModel"
        }    ];

    static getAttributeTypeMap() {
        return MobileMessageContentModel.attributeTypeMap;
    }
}

