/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class Scheduling {
    /**
    * The datetime informations the journey should be scheduled
    */
    'launchDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "launchDate",
            "baseName": "launch_date",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Scheduling.attributeTypeMap;
    }
}

