/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { SearchDataFilterDTO } from './searchDataFilterDTO';

export class SearchDataRequestModel {
    'fields': Array<string>;
    'filters'?: Array<SearchDataFilterDTO>;
    'skip'?: number;
    'take'?: number;
    'orderBy'?: string;
    'orderByDirection'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<SearchDataFilterDTO>"
        },
        {
            "name": "skip",
            "baseName": "skip",
            "type": "number"
        },
        {
            "name": "take",
            "baseName": "take",
            "type": "number"
        },
        {
            "name": "orderBy",
            "baseName": "order_by",
            "type": "string"
        },
        {
            "name": "orderByDirection",
            "baseName": "order_by_direction",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SearchDataRequestModel.attributeTypeMap;
    }
}

