/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ErrorDTO } from './errorDTO';

export class SearchDataResponseModel {
    'fields'?: Array<string>;
    'data'?: Array<Array<object>>;
    'resultCode'?: SearchDataResponseModel.ResultCodeEnum;
    /**
    * In case loading the data fails, this property contains the list of validation errors.
    */
    'errors'?: Array<ErrorDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<string>"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Array<object>>"
        },
        {
            "name": "resultCode",
            "baseName": "result_code",
            "type": "SearchDataResponseModel.ResultCodeEnum"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ErrorDTO>"
        }    ];

    static getAttributeTypeMap() {
        return SearchDataResponseModel.attributeTypeMap;
    }
}

export namespace SearchDataResponseModel {
    export enum ResultCodeEnum {
        Failed = <any> 'Failed',
        Succeeded = <any> 'Succeeded',
        PartiallySucceeded = <any> 'PartiallySucceeded',
        ValidationFailed = <any> 'ValidationFailed',
        NotFound = <any> 'NotFound',
        ServiceUnavailable = <any> 'ServiceUnavailable',
        InternalServerError = <any> 'InternalServerError'
    }
}
