/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class SendInWaves {
    'numberOfWaves'?: number;
    'itemsPerWave'?: number;
    'intervalInMinutes'?: number;
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfWaves",
            "baseName": "number_of_waves",
            "type": "number"
        },
        {
            "name": "itemsPerWave",
            "baseName": "items_per_wave",
            "type": "number"
        },
        {
            "name": "intervalInMinutes",
            "baseName": "interval_in_minutes",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SendInWaves.attributeTypeMap;
    }
}

