/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class TriggerJourneyEntryPointsRequest {
    /**
    * The id of the user on the current context (eg. default 0, same as Anonymous)
    */
    'userId'?: number;
    /**
    * The parameter and the value of that parameter that needs to be processed.
    */
    'parameterValues'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number"
        },
        {
            "name": "parameterValues",
            "baseName": "parameter_values",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return TriggerJourneyEntryPointsRequest.attributeTypeMap;
    }
}

