/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class TriggerJourneyEntryPointResponse {
    /**
    * A generic code indicating what the state of the request is.
    */
    'resultCode'?: TriggerJourneyEntryPointResponse.ResultCodeEnum;
    /**
    * The type of result the body may contain when the call is succesful
    */
    'resultType'?: TriggerJourneyEntryPointResponse.ResultTypeEnum;
    /**
    * The result of the current request when succeeded.
    */
    'body'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resultCode",
            "baseName": "result_code",
            "type": "TriggerJourneyEntryPointResponse.ResultCodeEnum"
        },
        {
            "name": "resultType",
            "baseName": "result_type",
            "type": "TriggerJourneyEntryPointResponse.ResultTypeEnum"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TriggerJourneyEntryPointResponse.attributeTypeMap;
    }
}

export namespace TriggerJourneyEntryPointResponse {
    export enum ResultCodeEnum {
        Failed = <any> 'Failed',
        Succeeded = <any> 'Succeeded',
        PartiallySucceeded = <any> 'PartiallySucceeded',
        ValidationFailed = <any> 'ValidationFailed',
        NotFound = <any> 'NotFound',
        ServiceUnavailable = <any> 'ServiceUnavailable',
        InternalServerError = <any> 'InternalServerError'
    }
    export enum ResultTypeEnum {
        None = <any> 'None',
        Content = <any> 'Content',
        Redirect = <any> 'Redirect',
        Validation = <any> 'Validation',
        Error = <any> 'Error'
    }
}
