/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { RelationCustomFiltersDTO } from './relationCustomFiltersDTO';

export class UpdateListRelationRequest {
    'scope'?: string;
    'type'?: UpdateListRelationRequest.TypeEnum;
    'masterlistFieldName'?: string;
    'slavelistApiName'?: string;
    'slavelistFieldName'?: string;
    'constraints'?: Array<RelationCustomFiltersDTO>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpdateListRelationRequest.TypeEnum"
        },
        {
            "name": "masterlistFieldName",
            "baseName": "masterlist_field_name",
            "type": "string"
        },
        {
            "name": "slavelistApiName",
            "baseName": "slavelist_api_name",
            "type": "string"
        },
        {
            "name": "slavelistFieldName",
            "baseName": "slavelist_field_name",
            "type": "string"
        },
        {
            "name": "constraints",
            "baseName": "constraints",
            "type": "Array<RelationCustomFiltersDTO>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateListRelationRequest.attributeTypeMap;
    }
}

export namespace UpdateListRelationRequest {
    export enum TypeEnum {
        OneToOne = <any> 'OneToOne',
        OneToMany = <any> 'OneToMany',
        ManyToOne = <any> 'ManyToOne'
    }
}
