/**
 * Selligent Marketing Cloud API
 * Click the endpoint to see details. In the Parameters-section, we show an example of how the data you send along with the api-call looks like.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class UpdateCustomEventRequestModel {
    /**
    * Name of the custom event.
    */
    'name'?: string;
    /**
    * Description about the custom event.
    */
    'description'?: string;
    /**
    * Tags associated with the custom event.
    */
    'tags'?: Array<string>;
    /**
    * Represents Transaction Field of the custom event
    */
    'transactionField'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "transactionField",
            "baseName": "transaction_field",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCustomEventRequestModel.attributeTypeMap;
    }
}

